# Generated by Django 4.2.2 on 2023-06-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='descreption',
            field=models.TextField(default='', max_length=270),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
