# Generated by Django 4.2.2 on 2023-06-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='instgram',
            new_name='instagram',
        ),
    ]
