# Generated by Django 4.2.2 on 2023-06-13 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoitment',
            name='appoitment_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
