# Generated by Django 4.2.2 on 2023-06-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoitment', '0003_alter_appoitment_appoitment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoitment',
            name='appoitment_data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appoitment',
            name='appoitment_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
