# Generated by Django 4.2.2 on 2023-06-16 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_service_descreption_alter_service_image'),
        ('dentist', '0002_rename_instgram_doctor_instagram'),
        ('appoitment', '0008_alter_appoitment_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoitment',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='appoitment',
            name='server',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='service'),
        ),
        migrations.AddField(
            model_name='appoitment',
            name='doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dentist.doctor', verbose_name='doctor'),
        ),
    ]
